# Exploratory Data Analysis and Insights on Pima Indians Diabetes Dataset Using Pandas

### Beginner-Level Pandas Practice Notebook

This notebook is designed for beginners who are learning how to work with datasets using **Pandas**.

The exercises focus on simple and important Pandas operations such as:

- Loading a CSV file
- Understanding rows and columns
- Checking data types
- Selecting columns
- Using `loc` and `iloc`
- Checking missing values
- Finding unique values
- Filtering records
- Using `query()`
- Creating new columns
- Using `apply()` and `lambda`
- Renaming and dropping columns
- Exporting a DataFrame

## About the Dataset

The **PimaIndiansDiabetes.csv** dataset contains health-related measurements for **768 records**.

It contains **9 columns**:

| Column | Description |
|---|---|
| `TimesPregnant` | Number of times pregnant |
| `GlucoseConcentration` | Glucose concentration measurement |
| `BloodPrs` | Blood pressure measurement |
| `SkinThickness` | Skin thickness measurement |
| `Serum` | Serum-related measurement |
| `BMI` | Body Mass Index |
| `DiabetesFunct` | Diabetes function value |
| `Age` | Age of the person |
| `Class` | Diabetes outcome class represented by 0 or 1 |

### Important Observation

The dataset does not contain standard `NaN` missing values.

However, some health-related columns may contain **0 values**. For this beginner exercise, we will treat the dataset as provided and focus mainly on learning Pandas operations.

### Goal

Use Pandas to explore the dataset and answer simple questions about its structure and values.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **PimaIndiansDiabetes.csv** into a DataFrame named `df`.

In [ ]:
import pandas as pd

path = "C:/Users/Tasmiya/Desktop/lihatech/PimaIndiansDiabetes.csv"

f = pd.read_csv(path)

### Question 2
Display the first **5 rows** of the dataset.

In [ ]:
f.head(5)

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

### Question 3
Display the last **5 rows** of the dataset.

In [ ]:
f.tail(5)

,TimesPregnant,GlucoseConcentration,BloodPressure,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### Question 4
Find the total number of **rows and columns** in the dataset.

In [11]:
f.shape

(768, 9)

### Question 5
Display all the **column names** in the dataset.

In [6]:
f.columns

Index(['TimesPregnant', 'GlucoseConcentration', 'BloodPrs', 'SkinThickness',
       'Serum', 'BMI', 'DiabetesFunct', 'Age', 'Class'],
      dtype='object')

### Question 6
Display the **data type of each column**.

In [9]:
f.dtypes

TimesPregnant             int64
GlucoseConcentration      int64
BloodPrs                  int64
SkinThickness             int64
Serum                     int64
BMI                     float64
DiabetesFunct           float64
Age                       int64
Class                     int64
dtype: object

### Question 7
Display complete information about the DataFrame using `info()`.

In [10]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TimesPregnant         768 non-null    int64
 1   GlucoseConcentration  768 non-null    int64
 2   BloodPrs              768 non-null    int64
 3   SkinThickness         768 non-null    int64
 4   Serum                 768 non-null    int64
 5   BMI                   768 non-null    float64
 6   DiabetesFunct         768 non-null    float64
 7   Age                   768 non-null    int64
 8   Class                 768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

## 2. Checking Missing Values

### Question 8
Check the number of **null values in each column** using `isnull()`.

In [12]:
f. isnull().sum()

TimesPregnant           0
GlucoseConcentration    0
BloodPrs                0
SkinThickness           0
Serum                   0
BMI                     0
DiabetesFunct           0
Age                     0
Class                   0
dtype: int64

### Question 9
Check the missing values again using `isna()`.

In [13]:
f.isna().sum()

TimesPregnant           0
GlucoseConcentration    0
BloodPrs                0
SkinThickness           0
Serum                   0
BMI                     0
DiabetesFunct           0
Age                     0
Class                   0
dtype: int64

## 3. Selecting Data

### Question 10
Select and display only the **Age** column.

In [14]:
f.Age

0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age, Length: 768, dtype: int64

### Question 11
Select and display the **Age, BMI, and Class** columns.

In [17]:
f[['Age', 'BMI', 'Class']]

     Age   BMI  Class
0     50  33.6      1
1     31  26.6      0
2     32  23.3      1
3     21  28.1      0
4     33  43.1      1
..   ...   ...    ...
763   63  32.9      0
764   27  36.8      0
765   30  26.2      0
766   47  30.1      1
767   23  30.4      0

[768 rows x 3 columns]

### Question 12
Display the first **10 rows** using DataFrame slicing.

In [26]:
f[:10]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

### Question 13
Using `iloc`, display the first **5 rows and first 4 columns**.

In [31]:
f.iloc[0:5,0:4]

   TimesPregnant  GlucoseConcentration  BloodPrs  SkinThickness
0              6                   148        72             35
1              1                    85        66             29
2              8                   183        64              0
3              1                    89        66             23
4              0                   137        40             35

### Question 14
Using `loc`, display rows **0 to 5** for the columns **GlucoseConcentration, BMI, and Age**.

In [37]:
f.loc[0:5, ['GlucoseConcentration', 'BMI', 'Age']]

   GlucoseConcentration   BMI  Age
0                   148  33.6   50
1                    85  26.6   31
2                   183  23.3   32
3                    89  28.1   21
4                   137  43.1   33
5                   116  25.6   30

## 4. Understanding Values

### Question 15
Display all the **unique values** available in the `Class` column.

In [39]:
f['Class'].unique()

array([1, 0])

### Question 16
Find the number of **unique values** in the `Class` column.

In [40]:
f['Class'].nunique()

2

### Question 17
Count how many records belong to **Class 0 and Class 1** using `value_counts()`.

In [41]:
f['Class'].value_counts()

Class
0    500
1    268
Name: count, dtype: int64

### Question 18
Find the number of unique ages present in the dataset.

In [42]:
f['Age'].nunique()

52

## 5. Basic Analysis

### Question 19
Find the **maximum age** in the dataset.

In [43]:
f['Age'].max()

np.int64(81)

### Question 20
Find the **maximum glucose concentration** in the dataset.

In [44]:
f['GlucoseConcentration'].max()

np.int64(199)

### Question 21
Find the **maximum BMI** in the dataset.

In [45]:
f['BMI'].max()

np.float64(67.1)

### Question 22
Find the **minimum age** in the dataset.

In [46]:
f['Age'].min()

np.int64(21)

## 6. Filtering Records

### Question 23
Display all records where **Age is greater than 40**.

In [49]:
f[f['Age'] > 40]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0
766,1,126,60,0,0,30.1,0.349,47,1

### Question 24
Display all records where **BMI is greater than 30**.

In [52]:
f[f[ 'BMI'] > 30]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### Question 25
Display all records where **TimesPregnant is greater than 5**.

In [53]:
f[f['TimesPregnant'] > 5]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
7,10,115,0,0,0,35.3,0.134,29,0
9,8,125,96,0,0,0.0,0.232,54,1
11,10,168,74,0,0,38.0,0.537,34,1
...,...,...,...,...,...,...,...,...,...
756,7,137,90,41,0,32.0,0.391,39,0
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0

### Question 26
Display only the records where **Class is equal to 1**.

In [55]:
f[f['Class'] == 1]

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

### Question 27
Using `query()`, display all records where **Age is greater than 50**.

In [56]:
f.query('Age > 50')

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

### Question 28
Using `query()`, display all records where **BMI is greater than 30 and Class is equal to 1**.

In [57]:
f.query("BMI > 30 and Class == 1")

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
11,10,168,74,0,0,38.0,0.537,34,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

## 7. Creating and Modifying Columns

### Question 29
Create a new column named **AgeGroup**. Store `Above 40` when Age is greater than 40; otherwise store `40 or Below`. Use `apply()` with a `lambda` function.

In [62]:
f['AgeGroup'] = f['Age'].apply(lambda x: 'Above 40' if x > 40 else '40 or Below')

### Question 30
Display the first **10 rows** after creating the `AgeGroup` column.

In [63]:
f.head(10)

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class,AgeGroup
0,6,148,72,35,0,33.6,0.627,50,1,Above 40
1,1,85,66,29,0,26.6,0.351,31,0,40 or Below
2,8,183,64,0,0,23.3,0.672,32,1,40 or Below
3,1,89,66,23,94,28.1,0.167,21,0,40 or Below
4,0,137,40,35,168,43.1,2.288,33,1,40 or Below
5,5,116,74,0,0,25.6,0.201,30,0,40 or Below
6,3,78,50,32,88,31.0,0.248,26,1,40 or Below
7,10,115,0,0,0,35.3,0.134,29,0,40 or Below
8,2,197,70,45,543,30.5,0.158,53,1,Above 40
9,8,125,96,0,0,0.0,0.232,54,1,Above 40

### Question 31
Count the values in the newly created **AgeGroup** column using `value_counts()`.

In [64]:
f['AgeGroup'].value_counts()

AgeGroup
40 or Below    574
Above 40       194
Name: count, dtype: int64

### Question 32
Remove the **AgeGroup** column using `drop()`.

In [66]:
f.drop('AgeGroup',axis = 1, inplace = True)
f

,TimesPregnant,GlucoseConcentration,BloodPrs,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### Question 33
Rename the column **BloodPrs** to **BloodPressure**.

In [68]:
f.rename(columns={'BloodPrs' :'BloodPressure'},inplace = True)

In [72]:
f.columns

Index(['TimesPregnant', 'GlucoseConcentration', 'BloodPressure',
       'SkinThickness', 'Serum', 'BMI', 'DiabetesFunct', 'Age', 'Class'],
      dtype='object')

## 8. Conversion and Export

### Question 34
Select and display only the **numeric columns** using `select_dtypes()`.

In [74]:
f.select_dtypes(include = 'number')

,TimesPregnant,GlucoseConcentration,BloodPressure,SkinThickness,Serum,BMI,DiabetesFunct,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

### Question 35
Convert the first **10 rows** of the DataFrame into a NumPy array using `to_numpy()`.

In [75]:
f.head(10)
f.to_numpy()

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

### Question 36
Save the DataFrame as a new CSV file named **Pima_Diabetes_Practice_Output.csv** without saving the index.

In [76]:
f.to_csv('Pima_Diabetes_Practice_Output.csv',index = False)

## End of Practice

Try to solve every question yourself before checking any solution.

The purpose of this notebook is to become comfortable with **basic Pandas operations** before moving to advanced topics such as:

- `groupby()`
- Aggregation
- Correlation
- Data visualization
- Machine Learning